---
- name: Start and enable services
  hosts: localhost
  become: yes
  vars_files:
    - vars/services.yaml

  tasks:
    - name: Enable and start docker
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Enable and start libvirtd
      ansible.builtin.service:
        name: libvirtd
        enabled: yes
        state: started

    - name: Enable and start LXC
      ansible.builtin.service:
        name: lxc
        enabled: yes
        state: started
    
    - name: Enable and start nftables
      ansible.builtin.service:
        name: nftables
        enabled: yes
        state: started
