---
- name: Install DNF and Flatpak packages on Fedora Linux
  hosts: localhost
  become: yes
  vars_files:
    - vars/packages.yaml
  
  tasks:
    - name: Ensure the system is up to date
      dnf:
        name: "*"
        state: latest
        update_only: yes

    - name: Install basic packages
      dnf:
        name: "{{ dnf_list }}" 
        state: present

    - name: Ensure Flatpak is installed
      dnf:
        name: flatpak
        state: present

    - name: Install Flatpak packages
      community.general.flatpak:
        name: "{{ flatpak_list }}"
        state: present
