---
- name: Install Pacman packages on Arch Linux
  hosts: localhost
  become: yes
  
  tasks:
    - name: Ensure the system is up to date
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install basic packages
      pacman:
        name: 
          - base-devel
          - git
          - neovim
          - code
        state: present
